#!/bin/bash -e

export ECOLOGY_CLUSTER_NAME=aws
read -p "AWS SSH Key Name: " AWS_KEYPAIR_NAME
export AWS_KEYPAIR_NAME
read -p "AWS SSH Private Key Path: " AWS_PRIVATE_KEY_PATH
export AWS_PRIVATE_KEY_PATH
echo
read -s -p "AWS Access Key ID: " AWS_KEY_ID
export AWS_KEY_ID
echo
read -s -p "AWS Access Key: " AWS_ACCESS_KEY
export AWS_ACCESS_KEY
echo
read -s -p "AWS Session Token: " AWS_SESSION_TOKEN
export AWS_SESSION_TOKEN
echo
